name: MemeFine
main: com.fobcode.mf.MemeFine
version: 1.0.0
commands:
    fine:
        usage: /<command>
        desc: Takes a certain amount of money from a user as punishment.
        aliases: [mf, memefine]
    mfreload:
        usage: /<command>
        desc: Reloads the config to avoid server reload.
        aliases: [mfree, mfreedoot, mfreeload, motherfuckerreload]
depend: [Vault]