notenoughmoney: "&cYou cannot fine them more than their balance!"
playerdoesntexist: "&cThat player does not exist or is offline!"
generalerror: "&cSomething went wrong"
nopermission: "&cYou do not have permission"
nouser: "&cYou must provide a player to fine"
nofineamount: "&cYou must provide an amount to fine the player."
noreason: "&cYou must provide a reason for the fine."
finedmessage: "&cYou have been fined %amount% %units% for %reason%."
finesuccess: "&2You fined %player%  %amount% %units% for %reason%."